---
- name: Ensure prometheus dir exists
  become: true
  file:
    path: /opt/prometheus
    recurse: true
    state: directory

- name: Ensure passenger_exporter is downloaded
  become: true
  get_url:
    url: https://github.com/jobscore/passenger_exporter/releases/download/{{prometheus_passenger_version}}/passenger_exporter_nginx
    dest: /tmp/passenger_exporter_nginx
    mode: 0755
  changed_when: false

- name: Ensure passenger_exporter is placed in the correct folder
  become: true
  copy:
    remote_src: true
    src: /tmp/passenger_exporter_nginx
    dest: /opt/prometheus/passenger_exporter_nginx
    mode: preserve

- name: Ensure the tmp file is removed
  become: true
  file:
    state: absent
    path: /tmp/passenger_exporter_nginx
  changed_when: false

- name: Ensure passenger_exporter service is configured
  become: true
  template:
    dest: /etc/systemd/system/prometheus-passenger-exporter.service
    src: passenger_exporter-service.j2
  notify:
    - restart prometheus_passenger

- name: Ensure passenger_exporter service is enabled
  become: true
  systemd:
    daemon_reload: true
    enabled: true
    name: prometheus-passenger-exporter.service
  notify:
    - restart prometheus_passenger
